config/routes.rb
Rails.application.routes.draw do


  get 'comments/new'

  get 'comments/edit'

  get 'comments/update'

  get 'comments/show'

  get 'comments/destroy'

  get 'comments/index'

	root 'home_pages#index'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
	resources :posts
  resources :comments
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #resources :microposts,          only: [:create, :destroy]
  #resources :relationships,       only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  default_scope ->{order(created_at: 'DESC')}
  validates :user_id, presence: true;
  validates :post_id, presence: true;
  validates :comment, presence: true, length:{maximum: 140}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user 
  def new
  end
  
  def create
    @post = Post.find_by(id: params[:comment][:post_id])
    
    @comment = @post.comments.build(comment_params)
    if @comment.save
      flash[:success] = "Comment Saved"
      redirect_to root_url
    else
      flash[:error] = "There was a problem saving your comment"
      redirect_to root_url
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  def index
  end
  private
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <br>
<li id="comment-<%=comment.id%>">
    <%=link_to image_tag comment.user.gravatar_url({size:30})%>
    <span class="user">
      <%= comment.user.name %> 
    </span>
    <%= comment.comment %>
    </li>
    <li>
      <p>
      <i>
        <%=time_ago_in_words(comment.created_at)%> ago.
      </i>
      </p>
    </li>

app/views/comments/_comment_form.html.erb
<%= bootstrap_form_for :comment, url: comments_path do |f| %>
    <%= f.text_area :comment, placeholder: "Compose new comment..." %>
    <%= f.hidden_field :post_id , :value=>post.id%>
    <%= f.hidden_field :user_id , :value=>current_user.id%>
  	<%= f.submit "Submit Comment", class: "btn btn-primary" %>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
RRRRromments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>